### ISSUE TITLE
Enhancement: Pornbay Support (and maybe HF, FC, ENT)

### ISSUE THREAD

**Issue by bunkmate5127** [bdbenim/stash-empornium#141]
Pornbay is very similar to Emp. Some differences:

- URL/Announce
- They have subtle differences in tags, mostly arising from different or non existent merges from their equivalent of the now defunct on Emp "tag team".
- Minor different categories (when's Emp going to finally delete them anyway?)

Otherwise I think it's all identical (importantly they all allow fapping and jerking as image hosts).

- [ ] Write default tag map. I'll volunteer myself for this.
- [ ] Add new button in stash for "PB".
- [x] Add pornbay.org to the userscript's default set of urls to match against
- [ ] Intelligent leveraging/re-use of 'work' (optional)—i.e. reuse of image urls, .torrent hashing (just replace the announce in the .torrent, instead of rehashing the whole thing), etc. 
- [ ] ???
- [ ] Profit

There's some gotchas with .torrents that I don't fully understand—they need to have some salt when they're made somehow so that a client can have two loaded at the same time for different trackers. I don't know if this salt gets added before the SHA1 hashes are generated, or indeed if it's possible to just change the announce URL and "other stuff that isn't the SHA1 hashes" and create a .torrent that's simultaneously loadable in your client. I know that changing the announce URL alone isn't enough to make your client load it as a second torrent (it'll think it has already loaded it), a bigger difference is required than this, but I don't fully understand it. Probably worth talking to L4G, NoobMaster, or mmgoodnow  (writers of the other popular upload tools L4G's upload script, GGbot, and cross-seed respectively) to understand this.

Might be worth considering this in the context of also: HappyFappy, Enthralled, and FemdomCult. They basically all have the same difficulty to add as pornbay. They're all luminance/gazelle clones of Emp. 

Ent and FC have more niche content that is unlikely to be in the stashdb server, or have primary scrapers in stash itself. But this is a _present time_ issue, and will probably improve over time (and having a project like this work with those sites will help bring about that change). Ent is basically dead since FC's revival (it was made as an FC replacement when FC went down). The default tag map for FC and Ent will accordingly be very difficult to write. HF is just a low volume site, but basically if you're adding one (PB) you may as well add the lot, because it doesn't really add any difficulty in my estimation (other than a tag map—but this can just be a token effort/placeholder file until someone comes and PR's it).

**Comment by bdbenim** [comment]
This makes sense to me. I wouldn't be surprised if this could be done with almost no change to the userscript and probably not too much changed on the backend.

This will also require updating the DB schema to add tag mappings for different trackers. I've been planning to integrate Alembic, which is a package that should make schema migrations easy, so this would be a good time to add it.

Regarding the torrents, it's generally the "source" value that allows the info hash to be different on different trackers, though it's not the only possible method. Empornium's source flag for example is "Emp". Unfortunately since this included in the hash, it can't just be changed without recalculating the hash. However, the torrent generation tasks could be executed in parallel so that even though it does take more computation, it shouldn't add significantly more time. It keeps the code simpler for now anyway to not try to reuse a torrent generated for another tracker, since functionality would have to be added to keep track of all the generated torrent files and their associated scenes. That's something we might want to implement eventually though. The other good news is that generating the torrents for different trackers is as easy as changing one argument in the `mktorrent` command. This source flag is always the same for a given tracker, and not linked to the user account in any way, so it will be easy to just hardcode it in for each tracker.

The main hiccup I can see would be the image URLs. I'm not sure about all the trackers you listed, as the only other one I'm on is HF, but its image host whitelist does not include emp's hosts - only imagebam, webmshare, and imgbox. This will require adding functionality to the image handler for at least one new image host, which could turn out to be time consuming (or not). A lot of the code is fairly spaghetti-like right now, so changing this might require rewriting other code as well. On the bright side, that would probably force the code to be better structured which will be helpful in the long run. There's also a good chance that one additional image host would allow URLs to be reused by at least some other trackers, e.g. if multiple trackers whitelist imagebam.

As I said I only have an account on HF of all the trackers you mentioned. Most likely I'll make the changes just for that tracker first, and then once that's working all I would need is for someone else to confirm that it works on other trackers too.

**Comment by bdbenim** [comment]
Just tested this on HF, and it's promising. Without changing anything in the userscript beyond adding the extra URL, everything worked correctly. The only issue was that the image URLs caused an error on the upload form because they're not from an approved host, but at least this means that the frontend shouldn't really need to change.

**Comment by bunkmate5127** [comment]
Right, HF doesn't allow fapping/jerking (I think it's more the other way, i.e. Emp's imagehosts don't allow HF to use them). PB, Ent, and FC all do however. PB and Ent staff have big cross-over with Emp. FC I'm significantly less familiar with. HF I'm also largely out of the loop on.

Adding a second image host just for HF does seem kind of a lot of work for a little pay off though. But it's good to build out secondary trackers where-ever possible, should the unthinkable ever happen to Emp. The present issues are proof enough of that.

Full lists of supported hosts:
- **Ent:** fapping.empornium.sx, jerking.empornium.ph
- **PB:** fapping.empornium.sx, jerking.empornium.ph, pstorage.space
- **FC:** fapping.empornium.sx, jerking.empornium.ph, imgbb.com, imgbox.com, pixxxels.cc, pimpandhost.com, postimage.org, fastpic.ru
- **HF:** imagebam.com, webmshare.com, imgbox.com

So if you were to implement a second imagehost, it'd be best for it to be imgbox (HF and FC).

 I'll see what I strings I can pull to get you into the relevant places.

**Comment by bdbenim** [comment]
Awesome, thanks for the info and the links! I'm expecting it will be pretty easy to update the image uploader to handle different hosts. The actual HTTP requests part is already handled by a separate function, so all that should be necessary is create another function for imgbox (or wherever) and then tell the image uploader which function to call depending on the tracker.

I'm working on the database changes right now, and I think it's just about done. Turns out it would have been better to include alembic from the very beginning, but I've pretty much figured out how to bootstrap it so it should work just fine. I'm hoping to have that completed here pretty soon and then I'll start on the next phase!

**Comment by bunkmate5127** [comment]
Ok try and check your emails, I think you should have FC and PB coming to you from the admin's there. Still waiting to hear back from Ent—so keep checking for the next few days.
