### ISSUE TITLE
Default config values result in AttributeError

### ISSUE THREAD

**Issue by dsrtusr88** [bdbenim/stash-empornium#17]
2023-10-07 10:08:33,824 - INFO - Reading config from /config/config.ini
2023-10-07 10:08:33,832 - INFO - Template "fakestash-v2" has a new version available in the default-templates directory
Traceback (most recent call last):
  File "/emp_stash_fill/emp_stash_fill.py", line 103, in <module>
    TITLE_DEFAULT = conf["backend"].get("title_default", "[{studio}] {performers} - {title} ({date}){resolution}").value # type: ignore
AttributeError: 'str' object has no attribute 'value'

**Comment by Asparghus** [comment]
Do you have "title_default = [{studio}] {title} - {performers} ({date}){resolution}" in your config.ini?
```
[backend]
## name of a file in templates/ dir
default_template = fakestash-v2
## where torrents are placed
torrent_directory = /torrents
## port that the backend listens on
port = 9932
## Title format
title_default = [{studio}] {title} - {performers} ({date}){resolution}
```

**Comment by bdbenim** [comment]
I'm renaming this issue, because it looks like this is a problem with how configupdater handles default values. If the setting is present in the config file, it returns an object of type `option`, but otherwise it returns a string. This will likely be an issue for all config options that use `.value` along with a default setting. Those will likely all have to be changed to handle this type discrepancy

**Comment by Asparghus** [comment]
> @Asparghus that works, is there documentation for those variables? hoping for a `date` that is `YY.MM.DD`

It writes as saved on your Stash
