### ISSUE TITLE
Error uploading image

### ISSUE THREAD

**Issue by dsrtusr88** [bdbenim/stash-empornium#26]
Animated WebP is not supported 

latest docker build

**Comment by bdbenim** [comment]
Is there an error message in your log?

**Comment by bdbenim** [comment]
Should be fixed now. Docker image v0.5.4 is building as I type this

**Comment by bdbenim** [comment]
Alright, second attempt. Should be fixed by 70a3da1, but I can't be sure until you test it out. The fix is in the latest docker build [bdbenim/stash-empornium:0.5.6](https://hub.docker.com/layers/bdbenim/stash-empornium/0.5.6/images/sha256-dffc9d90d6772b37cccc5edc8242ce7b9d3a4bf49a2521209a7b7f57d7efbe08)

**Comment by bdbenim** [comment]
Resolved in #37
